theme = "onedark"

[editor]
line-number = "relative"
color-modes = true

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "primary-selection-length", "position-percentage", "position"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
"esc" = ["flip_selections", "collapse_selection", "keep_primary_selection"]

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"

[keys.normal."+"]
b = ":sh cargo build"
r = ":sh cargo run"
t = ":sh cargo test"
