theme = "onedark"

[editor]
line-number = "relative"
true-color = true
color-modes = true
auto-completion = false

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "primary-selection-length", "position-percentage", "position"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"

[keys.normal."A-\\"]
S = [":pipe ccase -t screamingsnake", "delete_char_forward"]
c = [":pipe ccase -t camel", "delete_char_forward"]
k = [":pipe ccase -t kebab", "delete_char_forward"]
K = [":pipe ccase -t upperkebab", "delete_char_forward"]
l = [":pipe ccase -t lower", "delete_char_forward"]
p = [":pipe ccase -t pascal", "delete_char_forward"]
s = [":pipe ccase -t snake", "delete_char_forward"]
u = [":pipe ccase -t upper", "delete_char_forward"]
